version: "3"
services:
  app:
    build: .
    container_name: app
    # entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app-networks
  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    # entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
    # environment:
    #   - NG_HOST=app
    #   - NG_PORT=9000
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-networks
  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-networks
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge
